OptionTracker/Controllers/TickersController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using System.Web;
using API.Dtos;
using API.Helpers;
using Core.Specifications;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using OptionTracker.Data;
using OptionTracker.Models;
using OptionTracker.Services;

namespace OptionTracker.Controllers
{
    public class TickersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<TickersController> _logger;
        private readonly IApiService _apiService;

        public TickersController(ApplicationDbContext context, IApiService apiService,
            ILogger<TickersController> logger)
        {
            _context = context;
            _apiService = apiService;
            _logger = logger;
        }

        // GET: Ticker
        public async Task<IActionResult> Index([FromQuery] TickerSpecParams productParams)
        {
            var client = new HttpClient();

            productParams.PageSize = 50;

            var longurl = "https://core-api-qepiuuzgya-uc.a.run.app/api/Products";

            var uriBuilder = new UriBuilder(longurl);
            var query = HttpUtility.ParseQueryString(uriBuilder.Query);


            query["PageIndex"] = productParams.PageIndex.ToString();
            query["PageSize"] = productParams.PageSize.ToString();
            query["BrandId"] = productParams.BrandId.ToString();
            query["TypeId"] = productParams.TypeId.ToString();


            if (!string.IsNullOrEmpty(productParams.Sort))
            {
                query["Sort"] = productParams.Sort;
                ViewData["Sort"] = productParams.Sort;
            }

            if (!string.IsNullOrEmpty(productParams.Search)) query["Search"] = productParams.Search;


            uriBuilder.Query = query.ToString();
            longurl = uriBuilder.ToString();
            // Products?Sort=capDesc
            // Products?PageSize=50&PageIndex=1&Sort=capDesc
            // Products?PageIndex=2&PageSize=2&Sort=capDesc
            var answer = await client.GetFromJsonAsync<JsonDocument>(longurl);

            var tickers = JsonConvert
                .DeserializeObject<TickerToReturnDto[]>(answer.RootElement.GetProperty("data").ToString()).ToList();

            var count = answer.RootElement.GetProperty("count").GetInt32();


            return View(new Pagination<TickerToReturnDto>(productParams.PageIndex,
                productParams.PageSize, count, tickers));
        }

        [HttpPost("Tickers/GetOptionChartData/{ticker}")]
        public JsonResult GetOptionChartData(string ticker)
        {
            try
            {
                var sp = ticker.Split("_");
                var volumeAnal = _context.OptionChainRaw
                    .Where(m => m.Symbol == sp[0]).ToList();

                var dates = volumeAnal.Select(x => JsonConvert
                    .DeserializeObject<Dictionary<string, Dictionary<string, OptionContract[]>>>(
                        x.Data.RootElement.GetProperty("callExpDateMap").ToString()));

                var opData = dates
                    .SelectMany(x => x.Values)
                    .SelectMany(x => x.Values)
                    .SelectMany(x => x)
                    .Where(x => x.Symbol == ticker)
                    .OrderByDescending(x => x.QuoteTimeInLong)
                    .Take(30)
                    .ToList();

                var graph1 = opData.Select(x => new
                    {x = x.QuoteTimeInLong, y = new[] {x.Last, x.ClosePrice, x.LowPrice, x.HighPrice}}).ToArray();
                var SeriesVal = graph1;

                var graph2 = opData.Select(x => new {x = x.QuoteTimeInLong, y = new[] {x.TotalVolume}}).ToArray();

                var LabelsVal = graph2;
                return Json(new {success = true, series = SeriesVal, labels = LabelsVal, message = "success.!"});
            }
            catch (Exception ex)
            {
                return Json(new {success = false, message = "Some thing went Wrong.! unsuccessfull!"});
            }
        }

        // GET: Ticker/Details/5
        // [ResponseCache(VaryByHeader = "", Location = ResponseCacheLocation.Client, Duration = 30)]
        [HttpGet("Tickers/Details/{symbol}")]
        public async Task<IActionResult> Details(string symbol, [FromQuery] TickerSpecParams productParams)
        {
            if (symbol == null) return NotFound();
            var ticker = await _context.TickerSymbols
                .FirstOrDefaultAsync(m => m.Name.Equals(symbol.ToUpper()));

            if (ticker == null) return NotFound();

            var chainRaw = new OptionChainRaw();

            if (productParams.BrandId != null)
            {
                ViewData["Brand"] = productParams.BrandId;

                chainRaw = await _context.OptionChainRaw.Where(x =>
                        x.Symbol == ticker.Name)
                    .OrderByDescending(x => x.Id).FirstOrDefaultAsync();

                var day = chainRaw.Created.AddDays(-productParams.BrandId.GetValueOrDefault());

                chainRaw = await _context.OptionChainRaw.Where(x =>
                    x.Symbol == ticker.Name && x.Created.Date == day).FirstOrDefaultAsync();
            }
            else
            {
                ViewData["Brand"] = "0";
                chainRaw = await _context.OptionChainRaw.Where(x =>
                        x.Symbol == ticker.Name)
                    .OrderByDescending(x => x.Id).FirstOrDefaultAsync();
            }

            OptionContract[] s;


            if (productParams.TypeId == 1)
                s = JsonConvert
                    .DeserializeObject<Dictionary<string, Dictionary<string, OptionContract[]>>>(
                        chainRaw.Data.RootElement.GetProperty("putExpDateMap").ToString() ?? "")
                    .SelectMany(a => a.Value.Values)
                    .SelectMany(x => x).ToArray();
            else
                s = JsonConvert
                    .DeserializeObject<Dictionary<string, Dictionary<string, OptionContract[]>>>(
                        chainRaw.Data.RootElement.GetProperty("callExpDateMap").ToString() ?? "")
                    .SelectMany(a => a.Value.Values)
                    .SelectMany(x => x).ToArray();

            var dt = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc);
            var dtDateTime = dt.AddMilliseconds(s[0].QuoteTimeInLong.GetValueOrDefault()).ToLocalTime();

            var viewModel = new ChainResultViewModel
            {
                Ticker = ticker.Name,
                MarketCap = ticker.MarketCap,
                ClosePrice = ticker.ClosePrice,
                Created = dtDateTime,

                OptionsResults = s
                    .Select(both => new OptionResultViewModel
                    {
                        Description = both.Description,
                        Symbol = both.Symbol,
                        ChartCode = CreateChartCode(both.Description),
                        OpenInterest = both.OpenInterest,
                        Volume = both.TotalVolume,
                        ClosePrice = both.Last,
                        OpenInterestChange = both.OpenInterest - both.OpenInterest,
                        ClosePriceChange = both.Last - both.Last
                    })
                    .ToList()
            };

            if (!string.IsNullOrEmpty(productParams.Sort)) ViewData["Sort"] = productParams.Sort;
            if (productParams.TypeId != null) ViewData["Type"] = productParams.TypeId;


            productParams.PageSize = 50;

            if (string.IsNullOrEmpty(productParams.Sort) || productParams.Sort == "oiDesc")
                viewModel.OptionsResults = viewModel.OptionsResults.OrderByDescending(x => x.OpenInterest).ToList();

            if (productParams.Sort == "valueDesc")
                viewModel.OptionsResults = viewModel.OptionsResults.OrderByDescending(x => x.TotalValue).ToList();


            if (productParams.Sort == "oicDesc")
                viewModel.OptionsResults =
                    viewModel.OptionsResults.OrderByDescending(x => x.OpenInterestChange).ToList();

            if (productParams.Sort == "cpcDesc")
                viewModel.OptionsResults = viewModel.OptionsResults.OrderByDescending(x => x.ClosePriceChange).ToList();

            if (productParams.Sort == "cpDesc")
                viewModel.OptionsResults = viewModel.OptionsResults.OrderByDescending(x => x.ClosePrice).ToList();

            if (productParams.Sort == "volumeDesc")
                viewModel.OptionsResults = viewModel.OptionsResults.OrderByDescending(x => x.Volume).ToList();

            if (productParams.Search != null &&
                (productParams.Search.Equals("dweek") || productParams.Search.Equals("threed")))
            {
                var chainRaws = await _context.OptionChainRaw.Where(x =>
                        x.Data.RootElement.GetProperty("symbol").GetString() == ticker.Name)
                    .OrderByDescending(x => x.Id).Take(7).ToListAsync();

                viewModel = CreateChainResultViewModel(chainRaws, productParams.Search, ticker);
            }

            var c = viewModel.OptionsResults.Count;

            viewModel.OptionsResults =
                viewModel.OptionsResults.Take(productParams.PageSize).ToList();

            return View(new Pagination<ChainResultViewModel>(productParams.PageIndex,
                productParams.PageSize, c, new List<ChainResultViewModel> {viewModel}));
        }

        [HttpPost("Tickers/GetChartData/{ticker}")]
        public JsonResult GetChartData(string ticker)
        {
            try
            {
                var chainRaw = _context.OptionChainRaw.Where(x =>

OptionTracker/Controllers/TradersController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OptionTracker.Data;
using OptionTracker.Models;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using API.Dtos;
using Microsoft.EntityFrameworkCore.Query;

namespace OptionTracker.Controllers
{
    public class TradersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TradersController(ApplicationDbContext context)
        {
            _context = context;
        }

        //// GET: Traders
        //public async Task<IActionResult> Index(int id)
        //{
        //    Trader trader = null;

        //    if (id == null)
        //    {
        //        var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

        //  //      trader = await _context.Traders.Include(x => x.Tickers).FirstOrDefaultAsync(x => x.IdentityUserId == userId);

        //    }
        //    else
        //    {
        //      //  trader = await _context.Traders.Include(x => x.Tickers)
        //      //      .FirstOrDefaultAsync(m => m.Id == id);
        //    }

        //    if (trader == null)
        //    {
        //        return View(new List<TickerToReturnDto>());
        //    }

        //    return View(trader.Tickers);
        //}

        // GET: Traders/Details/5
        //[HttpGet("Traders/Details/{id}")]
        //[Route("Traders/Details")]
        //public async Task<IActionResult> Details(int? id)
        //{
        //    Trader trader;

        //    if (id == null)
        //    {
        //        var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

        //    //    trader = await _context.Traders.Include(x => x.Tickers).FirstOrDefaultAsync(x => x.IdentityUserId == userId);

        //    }
        //    else
        //    {
        //     //   trader = await _context.Traders.Include(x => x.Tickers)
        //     //       .FirstOrDefaultAsync(m => m.Id == id);
        //    }

        //    if (trader == null)
        //    {
        //        return View(new List<Ticker>());
        //    }

        //    return View(trader.Tickers);
        //}

        // GET: Traders/Create
        public IActionResult Create()
        {
            return View();
        }

        //// POST: Traders/Create
        //// To protect from overposting attacks, enable the specific properties you want to bind to.
        //// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("Id,IdentityUserId")] Trader trader)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(trader);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(trader);
        //}

        // GET: Traders/Edit/5
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //   var trader = await _context.Traders.FindAsync(id);
        //    if (trader == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(trader);
        //}

        // POST: Traders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        //// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("Id,IdentityUserId")] Trader trader)
        //{
        //    if (id != trader.Id)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(trader);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!TraderExists(trader.Id))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(trader);
        //}

        //// GET: Traders/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

        //    var trader = await _context.Traders.Include(x => x.Tickers).FirstOrDefaultAsync(x => x.IdentityUserId == userId);

        //    if (trader == null)
        //    {
        //        return NotFound();
        //    }


        //    return View(trader.Tickers.FirstOrDefault(x=>x.Id == id));
        //}

        // POST: Traders/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);

        //    var trader = await _context.Traders
        //        .Include(x => x.Tickers)
        //        .FirstOrDefaultAsync(x => x.IdentityUserId == userId);

        //    var ticker = trader.Tickers.FirstOrDefault(x => x.Id == id);

        //    trader.Tickers.Remove(ticker);

        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        //private bool TraderExists(int id)
        //{
        //    return _context.Traders.Any(e => e.Id == id);
        //}
    }
}

OptionTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<mini-profiler />
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Option Tracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-dark.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Option Tracker</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tickers"
                               asp-action="Index">Tickers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Traders"
                               asp-action="Details">Watchlist</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OptionActivities"
                               asp-action="Index">OptionActivities</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BookSummaries"
                               asp-action="Index">Crypto Options</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BookDetails"
                               asp-action="Index">Option Details</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Instruments"
                               asp-action="Index">Crypto Option Chains</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Positions"
                               asp-action="Index">Positions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PortfolioEths"
                               asp-action="Index">PortfolioEths</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="InstrumentHistories"
                               asp-action="Index">InstrumentHistories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DailyBalances"
                               asp-action="Index">DailyBalances</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                               asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
        </nav>
    </header>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - OptionTracker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>